experiment_dir: /output
save_checkpoint: true
max_epochs: 15
inference:
  n_forward_steps: 120
  n_samples: 1
  batch_size: 1
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: fourcastnet
  entity: ai2cm
train_data:
  batch_size: 8
  data_path: /traindata
  data_type: xarray
  engine: netcdf4
  num_data_workers: 4
validation_data:
  batch_size: 8
  data_path: /validdata
  data_type: xarray
  engine: netcdf4
  num_data_workers: 4
  n_samples: 123
stepper:
  builder:
    type: SphericalFourierNeuralOperatorNet
    config:
      embed_dim: 256
      filter_type: linear
      hard_thresholding_fraction: 1.0
      use_mlp: true
      normalization_layer: instance_norm
      num_blocks: 8
      num_layers: 8
      operator_type: dhconv
      scale_factor: 1
      separable: false
      spectral_layers: 3
      spectral_transform: sht
  normalization:
    global_means_path: /statsdata/residual/centering.nc
    global_stds_path: /statsdata/residual/scaling.nc
  optimization:
    enable_automatic_mixed_precision: false
    lr: 0.0005
    optimizer_type: FusedAdam
    scheduler:
      type: CosineAnnealingLR
  in_names:
  - PS
  - TS
  - T_0
  - T_1
  - T_2
  - T_3
  - T_4
  - T_5
  - T_6
  - T_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - U_0
  - U_1
  - U_2
  - U_3
  - U_4
  - U_5
  - U_6
  - U_7
  - V_0
  - V_1
  - V_2
  - V_3
  - V_4
  - V_5
  - V_6
  - V_7
  - SOLIN
  out_names:
  - PS
  - TS
  - T_0
  - T_1
  - T_2
  - T_3
  - T_4
  - T_5
  - T_6
  - T_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - U_0
  - U_1
  - U_2
  - U_3
  - U_4
  - U_5
  - U_6
  - U_7
  - V_0
  - V_1
  - V_2
  - V_3
  - V_4
  - V_5
  - V_6
  - V_7
  - LHFLX
  - SHFLX
  - surface_precipitation_rate
  - surface_upward_longwave_flux
  - FLUT
  - FLDS
  - FSDS
  - surface_upward_shortwave_flux
  - top_of_atmos_upward_shortwave_flux
  - tendency_of_total_water_path_due_to_advection
