experiment_dir: /pscratch/sd/j/jpduncan/ai2/ace-fv3gfs-original-normalization
save_checkpoint: true
validate_using_ema: true
max_epochs: 10
n_forward_steps: 1
inference:
  n_forward_steps: 1460
  forward_steps_in_memory: 146
  loader:
    start_indices:
      first: 0
      n_initial_conditions: 4
      interval: 1460
    dataset:
      data_path: /pscratch/sd/j/jpduncan/ai2/datasets/2023-12-03-fv3gfs/validdata/ic_0011
    num_data_workers: 8
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: fourcastnet-e3smv2
  entity: ai2cm
train_loader:
  batch_size: 8
  data_type: xarray
  num_data_workers: 8
  dataset:
    data_path: /not/used
validation_loader:
  batch_size: 16
  data_type: xarray
  num_data_workers: 8
  subset:
    stop: 1456
  dataset:
    data_path: /pscratch/sd/j/jpduncan/ai2/datasets/2023-12-03-fv3gfs/validdata/ic_0011
optimization:
  enable_automatic_mixed_precision: false
  lr: 0.0003
  optimizer_type: FusedAdam
  scheduler:
    type: CosineAnnealingLR
stepper:
  parameter_init:
    weights_path: /pscratch/sd/j/jpduncan/ai2/ace-fv3gfs/18004022/training_checkpoints/ema_ckpt.tar
    # overwrite all init params with ACE-FV3GFS pre-trained params
    # exclude_parameters:
    frozen_parameters:
      include:
        - device_buffer  # not trainable anyways
        - pos_embed
        - blocks.0.*
        - blocks.1.*
        - blocks.2.*
        - blocks.3.*
        - blocks.4.*
        - blocks.5.*
        - blocks.6.*
        - blocks.7.*
        - encoder.*
        - decoder.*
  builder:
    type: SphericalFourierNeuralOperatorNet
    config:
      embed_dim: 256
      filter_type: linear
      hard_thresholding_fraction: 1.0
      use_mlp: true
      normalization_layer: instance_norm
      num_layers: 8
      operator_type: dhconv
      scale_factor: 1
      separable: false
      spectral_layers: 3
      spectral_transform: sht
  loss:
    type: MSE
  normalization:
    global_means_path: /pscratch/sd/j/jpduncan/ai2/datasets/2023-12-03-fv3gfs/statsdata/fv3gfs-ensemble-ic0001-stats-residual-scaling-all-years-v2/centering.nc
    global_stds_path: /pscratch/sd/j/jpduncan/ai2/datasets/2023-12-03-fv3gfs/statsdata/fv3gfs-ensemble-ic0001-stats-residual-scaling-all-years-v2/scaling.nc
  ocean:
    surface_temperature_name: TS
    ocean_fraction_name: OCNFRAC
  in_names:
  - LANDFRAC
  - OCNFRAC
  - ICEFRAC
  - SOLIN
  - PHIS
  - PS
  - TS
  - T_0
  - T_1
  - T_2
  - T_3
  - T_4
  - T_5
  - T_6
  - T_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - U_0
  - U_1
  - U_2
  - U_3
  - U_4
  - U_5
  - U_6
  - U_7
  - V_0
  - V_1
  - V_2
  - V_3
  - V_4
  - V_5
  - V_6
  - V_7
  out_names:
  - PS
  - TS
  - T_0
  - T_1
  - T_2
  - T_3
  - T_4
  - T_5
  - T_6
  - T_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - U_0
  - U_1
  - U_2
  - U_3
  - U_4
  - U_5
  - U_6
  - U_7
  - V_0
  - V_1
  - V_2
  - V_3
  - V_4
  - V_5
  - V_6
  - V_7
  - LHFLX
  - SHFLX
  - surface_precipitation_rate
  - surface_upward_longwave_flux
  - FLUT
  - FLDS
  - FSDS
  - surface_upward_shortwave_flux
  - top_of_atmos_upward_shortwave_flux
  - tendency_of_total_water_path_due_to_advection
